// Per-category notes from the drafting pass: statements the writer was
// least sure of, so the dermatologist reviewer can start there. Rendered at
// the top of each category in review/handout-library-review.html.
import type { HandoutCategory } from "@/db/handout-templates";

export const REVIEWER_NOTES: Partial<Record<HandoutCategory, string[]>> = {
  conditions: [
    "Melanoma: follow-up 'often every 3 to 12 months for the first few years, then at least once a year'; genetic counseling if 2+ relatives had melanoma or relatives had pancreatic cancer; stop rule for unexplained symptoms over 2 weeks (weight loss, cough, headaches, bone pain); ask before starting vitamin D.",
    "SCC: more common with chronic leukemia; higher-risk SCC follow-up 'often every few months at first'. Atypical moles: mild atypia 'often no more treatment is needed, even if the edges were not clear' (practice varies).",
    "Seborrheic keratoses: 'many new growths appearing suddenly' stop rule (Leser-Trélat, unnamed). Lipomas: red flag 'larger than about 5 cm'.",
    "Ingrown toenails: cotton or floss under the nail edge (AAD, but debated); '3 to 5 days' of home care before calling is a default.",
    "Molluscum in adults: genital bumps suggest STI testing; many or large facial bumps suggest an immune check (worded gently).",
    "Hair loss: finasteride label warnings (lowers PSA, pregnancy handling, no blood donation, breast-change stop rule); a mood stop rule includes the 988 crisis line (cut if unwanted); spironolactone and minoxidil avoided in pregnancy and breastfeeding; biotin interferes with lab tests.",
    "Melasma (education): tranexamic acid pill users get an emergency stop rule for leg swelling, chest pain or shortness of breath; FDA mercury warning in skin lighteners also in the PIH handout.",
    "Seborrheic keratoses and skin tags: cosmetic-only removal 'often treated as cosmetic by insurance; ask us' (general statement, not clinic policy).",
    "Sources: guidelines cited by first author/journal/year only (Eisen 2021 AK; Kim 2018 BCC; Alam 2018 SCC; Swetter 2019 melanoma). Some AAD titles approximate: 'Nail changes a dermatologist should examine', 'Hyperpigmentation: How to fade dark spots', 'Hair shedding'.",
    "Acne: a stop rule names headache with vision change on an acne pill (tetracycline intracranial hypertension); some pills need a full glass of water, not right before lying down.",
    "Hives: 'sometimes we advise taking more than the label says; only if we told you' (guideline up-dosing); aspirin/NSAIDs listed as triggers.",
    "Lichen planus: skin disease 'often clears within about 1 to 2 years'; may check for hepatitis C; long-lasting oral or genital disease carries a small cancer risk. Lichen sclerosus: fingertip amount of steroid unless told otherwise; checks usually at least yearly; small SCC risk.",
    "Perioral dermatitis: rebound after stopping a steroid called expected; clearing in 2 to 3 months; rinse after steroid inhalers or nasal sprays and don't stop them without asking.",
    "Hand eczema: alcohol sanitizer often gentler than soap when hands aren't visibly dirty. Stasis dermatitis: ask before compression with arterial disease, diabetes or heart failure; leg skin easily becomes allergic to lanolin, fragrance and antibiotic ointments; one-sided swelling (possible clot) seen the same day; swelling with shortness of breath or chest pain, 911.",
    "Shingles: antivirals work best within 3 days; vaccine recommended for most adults 50+ and some younger immunocompromised adults (no dose count). Scabies: itch for 2 to 4 weeks after is normal; cream 'usually from the neck down'.",
    "Onychomycosis: 'waiting is a reasonable choice' if it doesn't bother you; terbinafine label stop rules (liver, taste or smell loss, low mood). Hyperhidrosis: antiperspirant at bedtime, washed off in the morning; 911 for sweating with chest pain. Tinea: 'keep using for the full time on the label' (no weeks given).",
    "Sources (inflammatory): page titles from memory, e.g. AAD 'Stasis dermatitis: Overview', NRS 'Rosacea triggers'. Guidelines by first author/journal/year: Reynolds 2024, Thiboutot 2020, Sidbury 2023, Davis 2024, Thyssen 2022, Clark 2015, Elmets 2021, Menter 2019, Alikhan 2019, Zuberbier 2022, Lewis 2018, Kalra 2014, Lipner and Scher 2019.",
  ],
  pediatric: [
    "Hemangioma: most growth done by about 5 months; high-risk features named (near eye, nose, lip, ear or diaper area; 5 or more; a large facial patch; beard area). Medicine 'with or right after a feeding' and warning signs (very sleepy, sweaty, cold or clammy, wheezing, not eating) clearly describe propranolol without naming it.",
    "Impetigo: back to school after at least 24 hours of antibiotics (hedged). A stop rule covers puffy face or cola-colored urine in the following weeks (post-strep kidney inflammation); decide if that belongs in a parent handout.",
    "Scabies (CDC): wash items used in the past 3 days, bag unwashables at least 3 days, back to school the day after treatment; treat scalp and face in babies; ask first for infants, pregnancy or breastfeeding.",
    "Insect repellent: no DEET under 2 months, no oil of lemon eucalyptus under 3 (AAP/CDC). Hydrocortisone: ask first under age 2.",
    "Teen acne: OTC adapalene 'for ages 12 and up' (OTC label); acne under age 7 or with early puberty signs needs a visit; retinoid pregnancy caution.",
    "Head lice: products differ on conditioner, second-treatment timing and household cleaning; hedged with 'check the label' and 'follow our directions'.",
    "Birthmarks: 6+ café-au-lait spots or armpit/groin freckling prompts a neurofibromatosis check; a forehead or periocular port-wine stain needs eye checks; earlier laser 'often works better'.",
    "Alopecia areata: 'newer medicines by mouth for some teens' (JAK inhibitors, unnamed). Tinea capitis: some oral antifungals absorb better with food; generic liver-symptom stop rule. Warts: salicylic acid warnings from the OTC label; duct tape omitted (mixed evidence).",
    "Infant sunscreen: shade and clothing first under 6 months; 'ask us' about small amounts on small areas (AAP/FDA).",
    "Sources: some HealthyChildren.org titles are approximate ('Skin Conditions in Newborns', 'Tinea Infections'). Papers cited by author/journal/year only: Krowchuk 2019, Nolt 2022, Balk 2011, Eichenfield 2013 and 2014, Reynolds 2024.",
  ],
  treatments: [
    "Bleach baths: about 1/2 cup regular-strength plain bleach per full tub, 1/4 cup per half tub, 1 teaspoon per gallon for a baby tub; 10 minutes, rinse after; often 2 to 3 times a week; ask if the bottle says concentrated. Check against clinic practice.",
    "5-FU: approximate phases (weeks 1 to 2, peak weeks 2 to 4, 1 to 3 weeks to heal); pet-toxicity warning; a whole-body-symptom stop rule reflecting the DPD-deficiency label warning.",
    "Imiquimod: apply at bedtime, wash off in the morning 'unless we told you otherwise'; skin color change 'can be permanent'.",
    "Calcineurin inhibitors: boxed warning framed as mainly animal high-dose data plus case reports, with reassuring large human studies since; pediatric age limits and 'avoid continuous long-term use' left out ('follow the schedule we gave you' keeps proactive use possible). Please confirm the framing.",
    "Oral antibiotics: upright at least 30 minutes; separate from minerals and antacids by 'a few hours'; probiotics not needed; birth-control interaction deliberately omitted; stop rules for severe headache with vision change, and minocycline pigmentation.",
    "Spironolactone: potassium 'usually not a problem for healthy young people', labs only if ordered; no potassium supplements or salt substitutes; 'a breast lump' stop rule; breastfeeding only 'tell us'.",
    "Minoxidil: toxic to cats (uncited); shedding the first few weeks to 2 months; results at 4 to 6 months, full effect about a year; one line on prescribed pills.",
    "Hydroquinone: 'a few months then a break' without exact cycles; lightening expected in 1 to 3 months, stop rule if none by about 3 months; warning against lighteners bought online.",
    "Biologics: check before any vaccine, live vaccines usually avoided; inject about 2 inches from the belly button; ask before a dose during an infection.",
    "Sun protection after skin cancer: nicotinamide deliberately omitted (mixed evidence); vitamin D only as 'food or supplements are safer than sun; ask us'. Sunscreen: about a teaspoon for face and neck; 3-year shelf life if undated.",
    "Sources less certain: the FDA consumer warning about pets and topical fluorouracil; Eisen et al. 2021 AAD actinic keratosis guideline (cited by year).",
  ],
  procedures: [
    "Bleeding: 20 minutes of firm pressure, repeat once, then call or go to urgent care/ER. The older post-procedure template says 15 minutes; pick one.",
    "Pain relief: acetaminophen usually first; ask before aspirin or ibuprofen.",
    "Before surgery: fish oil, vitamin E, ginkgo and garlic pills listed as 'ask us whether to pause' (no fixed number of days). Alcohol: avoid for a day or two before and after.",
    "Driving: a driver advised for surgery near the eye, on a hand or foot, larger repairs, or any calming medicine.",
    "Default timings, all hedged: stitches out in 1 to 2 weeks; keep the first bandage dry 24 to 48 hours; a graft's bolster dressing comes off in about a week; scars mature over 12 to 18 months; silicone for at least 2 to 3 months.",
    "PDT: 48 hours of light avoidance (per the ALA/MAL labels); 'sunscreen alone does not protect you'. No daylight-PDT wording.",
    "Patch testing: no sun on the back 1 to 2 weeks before; no topical steroids on the back about a week before; ask about (never stop alone) steroid pills or shots, methotrexate, cyclosporine, azathioprine, mycophenolate, biologics and JAK inhibitors; antihistamines can usually continue.",
    "Nail surgery: drainage 2 to 6 weeks after a chemical matrixectomy; regrowth 12 to 18 months for a toenail, about 6 months for a fingernail.",
    "Cantharidin: wash off at 'the time we told you, often a few hours' (no fixed hours); ring warts mentioned; tell us if pregnant before treatment.",
    "Steroid injections: repeats 'often every 4 to 6 weeks'; blood sugar may run higher for a day or two with diabetes.",
    "Phototherapy: most people improve after about 15 to 25 treatments; long-term skin cancer risk stated with a hedge.",
    "Infection: fever threshold 100.4 F (38 C); a tape-shaped itchy rash is likely an allergy (supports plain petrolatum over antibiotic ointment).",
    "Sources to confirm: the exact titles of 'MedlinePlus, Bleeding (first aid)', 'MedlinePlus, Skin abscess', 'AAD, How to treat an ingrown toenail'. Journal citations are author/journal/year only: Smack 1996 JAMA; Elmets 2019 JAAD (phototherapy); Heidelbaugh and Lee 2009 Am Fam Physician.",
  ],
  cosmetic: [
    "Isotretinoin isn't mentioned anywhere (policy). Instead the peel, resurfacing and pre-procedure handouts ask 'tell us about any acne medicine you have taken in the past year'; the usual 6 to 12 month wait isn't stated.",
    "Fillers: blocked-vessel signs are 'call us right away' stop rules, and vision change means go to the emergency room. The handout says hyaluronic acid filler can often be dissolved.",
    "Sclerotherapy: 911 stop rules for chest pain or shortness of breath, vision change, one-sided weakness or trouble speaking. Rare; confirm the clinic wants these.",
    "Common practice with weak evidence: botulinum toxin, stay upright about 4 hours with no rubbing or exercise that day; fillers, avoid dental work about 2 weeks before and after; no hot tubs or sweating for 24 to 48 hours after laser hair removal or microneedling; PRP, ibuprofen-type drugs 'may make PRP work less well'.",
    "Timings stated as 'usually': stop retinoids 3 to 7 days before (about a week before medium peels and resurfacing); avoid sun or tanning about 4 weeks before lights and lasers; session spacing for IPL, laser hair removal, tattoo removal, RF microneedling and PRP; cryolipolysis takes 35 to 60 minutes.",
    "RF microneedling: pacemaker or metal-implant screening included as a precaution; 'numb or sunken area' stop rule is a judgment call.",
    "Deoxycholic acid: 'several sessions at least 1 month apart'; the label's maximum of 6 sessions isn't stated. Cryolipolysis: paradoxical fat growth described in plain words; the painful bulge, nausea or vomiting (hernia) stop rule is extrapolated from the contraindication.",
    "PRP: a stop rule about vision change or a pale scalp comes from rare case reports; cut it if too alarming. PRP is not called off-label.",
    "Tattoo removal: some white, skin-tone and red cosmetic inks can turn darker with the laser. IPL: not right for every skin tone; brown spots darken ('coffee grounds') as expected.",
    "Sources: AAD and ASDS pages are cited generically ('ASDS patient information on ...'); exact page titles are not confirmed.",
  ],
};
